### ISSUE TITLE
Include support for different media types

### ISSUE THREAD

**Issue by Didel** [digitaledgeit/sass-breakpoints#3]
Currently it isn't possible to specify the type of media used, like so:

```
@media only screen and (min-width: 480px) {
    ...
}
```
See [W3 Schools](https://www.w3schools.com/css/css3_mediaqueries.asp)

I was looking for a way to specify _print_ as media type, which isn't possible.

**Comment by jameslnewell** [comment]
Hi @Didel. Thanks for raising the issue! I'm not really using this package anymore (I've moved to CSS-in-JS and have ported this [repo over](https://www.npmjs.com/package/styled-components-breakpoint) 😉 . Would you like to PR a solution and I'll review and publish it for you?

**Comment by Didel** [comment]
To be completely honest, I thought we were using this package in a project, but after posting this issue it appeared that the package wasn't removed successfully and we were already using another package to handle and manage the breakpoints. I thought I'd leave the issue, as it is something that I'd still expect to be possible. But for now this has no priority to me neither.
